### ISSUE TITLE
Packs are requested from invalid url

### ISSUE THREAD

**Issue by sadgb** [nikushi/minipack#29] opened 2020-01-20 13:53 UTC
Hello. 
I am using webpack-dev-server  on port 9000 and rails server on port 3000 
However for some strange reason rails generates paths like 
http://localhost:3000/packs/landing-95e755f46be9e49e5bfc.js
but should 
http://localhost:9000/packs/landing-95e755f46be9e49e5bfc.js

I am porting my application from webpack and done step by step instructions however this port mismatch makes me crazy. Could you please point me in the right direction ?

**Comment by nikushi** [comment] 2020-01-22 10:34
Helpers provided by minipack construct paths based on the base url served by Rails. So the behavior you reported is as expected.


To integrate Rails with webpack dev server, there is a way to use Rack::Proxy, then proxies requests for assets from your rails app to a backend webpack dev server e.g. https://gist.github.com/nikushi/4447f11f12b24db50b42608feeb848e2.

**Comment by nikushi** [comment] 2020-01-22 10:59
Let me close the issue because it is an expected behavior. Yet, we can still continue communication on the issue.

**Closed by nikushi** 2020-01-22 10:59 UTC

**Comment by sadgb** [comment] 2020-01-22 14:42
Thank you very much. I still have some issues, but packs are served correctly now.

**Comment by nikushi** [comment] 2020-01-23 03:49
Good to hear that. You can share your remaining issues. I may help you.

**Comment by sadgb** [comment] 2020-01-28 12:28
I found few issues on our side, not related to your awesome repo. 
Everything works like a charm now
